FROM python:3

ENV PYTHONUNBUFFERED 1
RUN apt-get update
RUN apt-get install gcc

COPY ./requirements.txt /requirements.txt

RUN pip install -r /requirements.txt

RUN mkdir /app
COPY . /app
WORKDIR /app

RUN pip install celery
# RUN python3 manage.py collectstatic --noinput